# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FirebasePractise' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FirebasePractise
pod 'Firebase'
pod 'Firebase/Firestore'
pod 'Firebase/Storage'
pod 'FirebaseUI/Storage'
 pod 'Firebase/Auth'
pod 'GoogleSignIn'
end
